### ISSUE TITLE
Defining a CSS class named "container" affects Debug panel

### ISSUE THREAD

**Issue by jimu** [boardgameio/boardgame.io#813]
After adding this CSS line to my client app, the Debug panel's collapse/expand arrows were mis-positioned

```css
<style>
    .container {width: 320px; height: 320px;}
</style>
```
![Debug Panel](https://i.imgur.com/gJbJiH2.png)
